// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whqrymbhwmzkeobxesbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndocXJ5bWJod216a2VvYnhlc2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODgyMzAsImV4cCI6MjA2NTU2NDIzMH0.C4p3FfurmFLku60lbzkxtNJZinVuCsYMqpaUXlHeV3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const realtimeDisabled =
  import.meta.env.VITE_DISABLE_REALTIME === 'true';

const realtimeOptions =
  !realtimeDisabled && typeof window !== 'undefined' && 'WebSocket' in window
    ? { transport: WebSocket }
    : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: realtimeOptions
});

// Expose for debugging in devtools.
if (import.meta.env.DEV && typeof window !== 'undefined') {
  (window as any).supabase = supabase;
}
